server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: web-async
# 配置线程池
web-async:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 100
  keepAliveSeconds: 60
  threadNamePrefix: web-async-